### ISSUE TITLE
Uma0 partition

### ISSUE THREAD

**Issue by zeromentu** [SKGleba/yamt-vita#10]
I configured yamt to mount sd2vita as ux0 and memory card as uma0, however it only mounts the sd2vita, when I go to Vita shell, there is no uma0 partition
![IMG_20190705_134256](https://user-images.githubusercontent.com/46009510/60724791-3e5be580-9f2f-11e9-8d16-3e854fb807ed.jpg)

**Comment by SKGleba** [comment]
check for other drivers, if you are sure yamt is the only one - delete yamt.cfg from ur0:tai/
