### ISSUE TITLE
VITA OS crash in DEX

### ISSUE THREAD

**Issue by arthurmv** [SKGleba/yamt-vita#11]
When I have YAMT enabled and go to Debug Settings system crash, if I disable YAMT it's OK.
![ERROR](https://i.ibb.co/TTx19f0/2019-07-16-215954.jpg)
- YAMT 3.0
- PCH-1001 Console
- CEX converted to REX with CEX2REX.

**Comment by SKGleba** [comment]
It is not compatible with any crappy firmware frankenstein builds.
Also do not use cex2rex if you want your console to survive next few firmware reinstalls.
