### ISSUE TITLE
[Question] Is there any code/way to detect if yamt is already installed and mounted?

### ISSUE THREAD

**Issue by alpakeno** [SKGleba/yamt-vita#12]
Like detect the kernel version if it's already running and mounted.

**Comment by SKGleba** [comment]
well you can search for the "yamt" module in loaded modulelist

**Comment by alpakeno** [comment]
tried to use _vshKernelSearchModuleByName but it didn't work.

**Comment by SKGleba** [comment]
Its "yamtKernel"
