### ISSUE TITLE
Crash in sleep mode?

### ISSUE THREAD

**Issue by d-rez** [SKGleba/yamt-vita#13]
This isn't a bug report per se because I'm not able to gather any logs (are there any?), but this never happened with Storage Manager for me, so reporting this down.

I had 85% battery left last night, played some Steins;Gate 0 for 30 minutes, put it to sleep (single button press), then this morning I tried to wake it up and it wouldn't. It was fully turned off and required a long press.

No biggie, the Vita booted up just fine from scratch and the plugin is working again, seems that no config options got modified , just that I lost all game progress since yesterday...

LCD model, 2000. I've had the plugin installed for about a week now I believe and this is the first occurrence  

EDIT: Not sure if this might be related in any way, but I've had the GPU frequency bug happen to me a day or two before and I didn't bother rebooting then

**Comment by SKGleba** [comment]
hmm i doubt that its related to yamt, the "crash" would be different. Next time try removing the SD2Vita when that happens, if it wakes up - its a yamt bug.

**Comment by d-rez** [comment]
Got it. I'll close this for now and if it appears again and I can reproduce the above, I'll reopen this issue

Thanks :)
