### ISSUE TITLE
Random Long Loads on Large SDs

### ISSUE THREAD

**Issue by RinMaru** [SKGleba/yamt-vita#14]
So this is an issue no matter what SD2VITA driver you use.
Vita 2000, FW3.60 Enso
I have this
[PNY-512GB MicroSD](https://www.amazon.com/dp/B07KD4XJLX/ref=cm_sw_em_r_mt_dp_U_x1dhEbPGZ968B)
Plus SD2VITA 5.0.

Anyways it seems theres some random freezes or long loading, whatever you prefer to call it. 
Example being you can click on a Bubble in the live area and the bubble will move to the center of the screen as it does while loading in the background and stuff but will sit there for about 30sec or longer. while this isnt a complete freeze since you can swipe out of it and interact with the UI it is a rather abnormal load time and it can happen in game when saving or other areas.

**Comment by SKGleba** [comment]
Shitty/Slow MicroSD card.

**Comment by RinMaru** [comment]
> Shitty/Slow MicroSD card.

do you have a suggested brand? thats the fastest SD card you can find outside sandisk you crazy?

**Comment by evertonstz** [comment]
> > Shitty/Slow MicroSD card.
> 
> do you have a suggested brand? thats the fastest SD card you can find outside sandisk you crazy?

It is, did you test its reading and writing speeds? Depending were you got you got you might have a counterfeit unit. I have the same SD and it works fine, the problem is in your side unfortunately.

**Comment by RinMaru** [comment]
Writing speeds went from 90mb+ read speeds i have no clue. its deff loading faster but sometimes "Rarely" some things will hang. I got the card from the same link i showed

**Comment by evertonstz** [comment]
> Writing speeds went from 90mb+ read speeds i have no clue. its deff loading faster but sometimes "Rarely" some things will hang. I got the card from the same link i showed

Is it new? Could be your sd/sd2vita is starting to malfunction. Might be a good idea to get other (smaller/other brand) card to test if you can reproduce the problem. Unfortunately I don't think there's anything that can be done software side.

**Comment by RinMaru** [comment]
Brand new got it like 5 days ago and got the SD2Vita a week ago. I have a 256GB SD Card and it had the same issues.

**Comment by SKGleba** [comment]
Oh ok, the brand is not popular here so no idea, i assumed that it was a knockoff.

Anyways: 
- Did you try with smaller SD cards?
- What is your sd2vita adapter (model or description) ?

**Comment by RinMaru** [comment]
[SD2VITA 5.0](https://www.amazon.com/Funturbo-Ultimate-Version-SD2Vita-Adapter/dp/B07F63FPT3/ref=sr_1_2?keywords=sd2vita&qid=1579007073&sr=8-2) 

Ive gone as small as 256GB SD and it presented the same issue.  

UPDATE- after looking at a vid testing UNIT13 my card was faster (Watched and started my game at the same time as the video and booted faster then the video). I dont think this is really a big issue but disconnecting from WiFi seems to get rid of lag in some cases. I guess this isn't really an issue after all. Though i find the live area bubbles hanging a bit weird but that's a problem with all SD2Vita plugins so maybe one will fix the issue or not. anyways Thanks for your Better SD2Vita driver I've been switching around testing diff ones and this one is the fastest
