### ISSUE TITLE
What are the steps to compile?

### ISSUE THREAD

**Issue by evertonstz** [SKGleba/yamt-vita#15]
I'm having some troubles compiling the source code. I'm runing cmake and make inside `./plugin/kernel and ./plugin/user` resulting in `yamt.skprx` and `yamt.suprx`, moved those two files into `./plugin`. But I'm not able to compile `yamt_360.skprx` or `yamt_360.suprx`, therefore when I run make in the root to build the .apk I get the following error:

```
Scanning dependencies of target yamt.self
[ 50%] Converting to Sony ELF yamt.velf
make[2]: Circular CMakeFiles/yamt.self <- yamt.self dependency dropped.
make[2]: Circular yamt.self <- yamt.self dependency dropped.
[ 60%] Creating SELF yamt.self
[ 60%] Built target yamt.self
Scanning dependencies of target yamt.vpk
[ 70%] Generating param.sfo for yamt.vpk
make[2]: *** No rule to make target 'plugin/yamt_360.skprx', needed by 'yamt.vpk'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:81: CMakeFiles/yamt.vpk.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by SKGleba** [comment]
Yeaaah the cmake file needs to be rewritten.
For now you need to compile the user plugin and move it to /plugin/yamt.suprx, then compile the kernel plugin and move it to /plugin/yamt_FIRMWARE.skprx.

**Comment by evertonstz** [comment]
so can I just rename the yamt.skprx to yamt_360.skprx and yamt_365.skprx? Are they all the same file with different names?

**Comment by SKGleba** [comment]
Nop, 3.65 one compiled with the 3.65 libs and offsets (-DNEWFW set).

**Comment by AlC4pwn** [comment]
Were you able to compile it? I moved the .suprx and .skprx files but I'm still getting the same error.

**Comment by evertonstz** [comment]
> Were you able to compile it? I moved the .suprx and .skprx files but I'm still getting the same error.

I was not. I'm gonna wait for the cmakes to be rewritten.

**Comment by AlC4pwn** [comment]
I think I understand what you're saying, when the kernel plugin is compiled you have to add the correct offset for 360 or 365 and then rename yamt.skprx to the matching version. The only thing is, what is the proper command for cmake with the -DNEWFW offset? Also, if you just do the normal 'cmake .&& make' in the kernel directory is that yamt_360.skprx?
