### ISSUE TITLE
No vpk available in assets

### ISSUE THREAD

**Issue by Satria2601** [SKGleba/yamt-vita#16]
Hi. I am planning to use this plugin, but I can't seem to find the vpk file on the releases tab.  It only shows zip file without the .vpk.  Thank you.

**Comment by evertonstz** [comment]
O think SKG won't release .vpk anymore. Or at least until it's 100% stable.

You probably can blame it on the kids that can't read and bricked their consoles with enso_ex.

**Comment by Satria2601** [comment]
> O think SKG won't release .vpk anymore. Or at least until it's 100% stable

Thanks a lot, that explains it.
