### ISSUE TITLE
soft brick on v4.0 stable

### ISSUE THREAD

**Issue by K4thos** [SKGleba/yamt-vita#20]
Hi,
Looks like I've soft bricked my vita 1000 3.60 enso.

Here is what I did:
1. Uninstalled storagemgr
2. Install yamt v4.0 full version via vpk
3. Enable yamt with following settings:
- ux0: USB/PSVSD
- uma0: sd2vita
legacy mode not enabled
4. At this point everything worked fine but I've noticed that xmc0 partition that in storagemgr was mounted to 32GB vita memory stick (MCD) didn't work here so I've mounted it in yamt as follows:
- xmc0: MCD (all default settings)

After reboot the vita goes into infinite loop of enso logo that shows up and disappears constantly. After force quiting the system by holding power for sereval seconds I can enter vita Safe Mode but after exiting it I'm once again in the endless startup loop.

L-hold-startup (used to disable plugins) doesn't seem to work - same infinite startup loop.

Any ideas or the vita can be tossed to bin?

**Comment by K4thos** [comment]
good news, restoring the system from Safe Mode fixed the issue. Enso is gone, although I should be able to restore everything.

Feel free to close the issue although it may be worth investigating why xmc0 mounting leads to it.

**Comment by SKGleba** [comment]
if you set as all default then it will attempt to mount custom-partitioned memcard as one partition leading to a bootloop that can be fixed by holding volume up with enso_ex v4 or reinstalling with default enso.

**Comment by soup6020** [comment]
Same issue, volup just leads to the boot process getting stuck at the PSVITA logo

**Comment by soup6020** [comment]
I installed it overtop a version of YAMT I had built from master in July
