### ISSUE TITLE
gro0 not mounted from custom partitions

### ISSUE THREAD

**Issue by BenMitnicK** [SKGleba/yamt-vita#21]
gro0 not mounted maybe it's normal

I try 

ux0 => SD2Vita and UMA0 => Memory card it work on my slim and fat vita

Now I want play game with my GameCard i try this

ux0 => Memory Card and UMA0 => Default and gro0 from custom partitons

Device => gcd
Partition Type => ign
Partition => userext
Chek if => Memory Card is present
The check must => Succees

ux0 and uma it's ok but gro0 not mounted but when I use this option 

Drivers Settings => Developer options => Reset the YAMT storage config

gro0 mounted correctely

Why I can't mounted gro0 from custom partitions ??

**Comment by SKGleba** [comment]
gamecard partitions are -gamero and -gamerw. Unless your gamecard has a -userext partition it will not work
