### ISSUE TITLE
psvsd can't be accessed after sleep

### ISSUE THREAD

**Issue by MegaPramuk** [SKGleba/yamt-vita#22]
After a longer period of time, the psvsd (seemingly) powers off and yamt is unable to power it on again or rather be able to access it/the micro SD, having to reboot the Vita.

I tried both the experimental USB patches and forcing the legacy mode being on together and only one at a time but neither worked.
Also, where does the logfile get created at?
I had looked via VitaShell in several locations but didn't find anything.

**Comment by SKGleba** [comment]
Yeah, use usbmc/storageMgr for now if the Yamt fails, i will work on it when i have time.
