### ISSUE TITLE
400GB card's

### ISSUE THREAD

**Issue by Shadow322** [SKGleba/yamt-vita#23]
YAMT formatting to TexFAT and StorageFormat will not format the card to TexFAT when placed into pc says its fat32

**Comment by Masamune3210** [comment]
I may be wrong but doesn't texfat still show up as exact and TFAT as fat32 to desktop windows? if I am remembering correctly the desktop versions don't technecally support them so they just show up as their normal versions

**Comment by Shadow322** [comment]
Other people reported on discord that it will show up as exfat on Windows so there is a problem with your tools and 400GB cards

**Comment by SKGleba** [comment]
YAMT can format up to 2TB, if it doesnt work it means the sd card is not compatible with YAMT.
