### ISSUE TITLE
Once the SD Card is formatted in TexFAT, if I insert the SD card on Windows it is no longer recognized.

### ISSUE THREAD

**Issue by Vinnievovi** [SKGleba/yamt-vita#24]
If this is normal, would it be possible to create software that allows Windows to recognize the TexFAT format?

**Comment by SKGleba** [comment]
It is definitely not normal, in fact texfat is owned by MS lol. Does the vita recognize it just fine? Can you usb-mount vita vitashell?

**Comment by Vinnievovi** [comment]
Yes, with vitashell it works, even connecting via USB with the PC, but if I insert only the SD card in the PC with different adapters it does not recognize it.

**Comment by SKGleba** [comment]
Vitashell just works as a sd2vita adapter, weird that sd adapters fail. What if you format it to fat32?

**Comment by Vinnievovi** [comment]
In fat32 it works great. It is recognized by the PC. Maybe it could be a problem with my PC. I have Windows 7 and the SD card is 256gb.

**Comment by SKGleba** [comment]
yeah, maybe win7 has problems with recognizing it
