### ISSUE TITLE
Crash when running the installer

### ISSUE THREAD

**Issue by gnuton** [SKGleba/yamt-vita#4]
Hi, I m running 3.65 orig firmware. removed storagemgr from tai config. Rebooted. Ran encore, Installed yamt-basic 1.0 from home Rew Vita app. 
When the yamt basic starts it crashes after saying that it has not found the spec file ur0:tai/ then it copies it correctly, after it added the entry to tai boot config then it crashes.
Does it require Enso or what?

**Comment by gnuton** [comment]
I checked the code and I dunno actually know yet why it stops. BTW it doesn't rename the temp boot file. BTW why don't you just run the skprx in the config? What's the difference?

**Comment by SKGleba** [comment]
yes it requires enso because its designed to run low level, it may cause issues if loaded after appmgr.

the crash will be fixed in next ver
