### ISSUE TITLE
External ux0 patch setting disables itself and then does not work properly

### ISSUE THREAD

**Issue by SKGleba** [SKGleba/yamt-vita#5]
Steps to reproduce: ?

Solution: remove ur0:tai/yamt.cfg.

The bug is being investigated, for now it looks like its sonys fault.

**Comment by RinMaru** [comment]
does this bug make this plugin unusable?

**Comment by SKGleba** [comment]
It makes it rather unstable.

**Comment by RinMaru** [comment]
tried yamt lite and seems to work flawlessly (due to no config file). Im amazed at how fast it runs.

**Comment by SKGleba** [comment]
Fixed in 3.1
