### ISSUE TITLE
SD2Vita with Memory Card Sleep problem

### ISSUE THREAD

**Issue by Schn1ek3** [SKGleba/yamt-vita#6]
When the Vita wakes up from sleep mode, the Vita hangs up. After a restart everything goes again. I have the SD2Vita as ux0 and the memory card as uma0 mounted.

**Comment by SKGleba** [comment]
hm, didnt encounter this problem, nor my testers did, whats your sd2vita setup (model, cap etc)?

**Comment by Schn1ek3** [comment]
I looked again and found out it was not because of the MemoryCard, sorry. It is due to the internal memory, which I have mounted as grw0 (PSV1000 with IMCunlock). I've mounted this with int, ign and userext.
I have SD2Vita v5 (128gb) as ux0 and MemoryCard as uma0.
