### ISSUE TITLE
[Question] about mounting xmc0/imc0 as ux0.

### ISSUE THREAD

**Issue by alpakeno** [SKGleba/yamt-vita#7]
From readme text:

>     This plugin patches xmc0/imc0 as ux0, you won't be able to separately mount those
>         i.e you can't mount xmc0 while ux0 is set to sd2vita.

When using gamesd plugin to mount gamecard (sd2vita) as ux0, we can mount memorycard as xmc0 using VitaShell...

Mounting uma0 is not possible in VitaShell for PSV1000 because it requires a USB connection.

So why not yamt do the same?

**Comment by SKGleba** [comment]
use yamt to mount uma0, and i explained why you cant use xmc0/imc0 if binded
