### ISSUE TITLE
"could not find boot_config.txt in ur:tai/  !"

### ISSUE THREAD

**Issue by paulomatosx** [SKGleba/yamt-vita#8]
It happen when start bubble.

Here am using vita tv running fw 3.65, with enso.
I disable my plugin usbmc with (#)...
happen same with it usbmc activate...

I was trying version 3.0, I'm going to try old version it.

**Comment by paulomatosx** [comment]
version basic created the "file boot_config_temp.txt"
with 2 lines
0000 # YAMT
0001 - load ur0:tai/yamt.skprx
0002

now I'm going to try manual installation

**Comment by paulomatosx** [comment]
it's working now.

**Comment by asb64** [comment]
Hey I'm having the same issue, but I'm not much of a coder can you help please
